"""Criada a model UserProfile

Revision ID: 1d75d8acedf2
Revises: 20f0877c07ab
Create Date: 2022-08-27 17:50:24.815786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d75d8acedf2'
down_revision = '20f0877c07ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_users_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tb_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_users_profiles')
    # ### end Alembic commands ###
