"""Criada a model Transaction

Revision ID: 87db4b778bfe
Revises: 3aad3b94560c
Create Date: 2022-08-27 18:12:23.981811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87db4b778bfe'
down_revision = '3aad3b94560c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('debit_account_id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['tb_financial_accounts.id'], ),
    sa.ForeignKeyConstraint(['debit_account_id'], ['tb_financial_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_transactions')
    # ### end Alembic commands ###
