# Generated by Django 4.1.2 on 2022-10-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe um gênero literário (Ficção Científica, Terror, etc)', max_length=200)),
            ],
            options={
                'db_table': 'tb_generos',
            },
        ),
    ]
