# Generated by Django 4.1.2 on 2022-10-08 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=100)),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='★')),
                ('data_de_falecimento', models.DateField(blank=True, null=True, verbose_name='✟')),
            ],
            options={
                'ordering': ['sobrenome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sumario', models.TextField(help_text='Informe uma breve descrição do livro', max_length=100)),
                ('isbn', models.CharField(help_text='Informe o ISBN (13 caracteres)', max_length=13, verbose_name='ISBN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='Informe um gênero para esse livro', to='catalogo.genero')),
            ],
            options={
                'db_table': 'tb_livros',
            },
        ),
        migrations.CreateModel(
            name='CopiaLivro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID da cópia', primary_key=True, serialize=False)),
                ('impressao', models.CharField(max_length=200)),
                ('devolucao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Manutenção'), ('e', 'Emprestado'), ('d', 'Disponível'), ('r', 'Reservado')], default='m', help_text='Disponibilidade da cópia', max_length=1)),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo.livro')),
            ],
            options={
                'db_table': 'tb_copias',
                'ordering': ['devolucao'],
            },
        ),
    ]
