"""Adicionado campo password na model User

Revision ID: 7acd9acd5fa8
Revises: 4c8c6e17f47f
Create Date: 2022-08-20 14:57:01.127313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acd9acd5fa8'
down_revision = '4c8c6e17f47f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_users', sa.Column('password', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_users', 'password')
    # ### end Alembic commands ###
