"""Criada a model OrderDetail

Revision ID: a61b7c971054
Revises: d1ebeeb72e3e
Create Date: 2022-08-20 17:41:39.328619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61b7c971054'
down_revision = 'd1ebeeb72e3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_orders_details',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['tb_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['tb_products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_orders_details')
    # ### end Alembic commands ###
