# Generated by Django 4.1.1 on 2022-09-24 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tb_clubs',
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_rounds',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField()),
                ('date', models.DateField()),
                ('away_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_club', to='core.club')),
                ('home_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_club', to='core.club')),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.round')),
            ],
            options={
                'db_table': 'tb_matches',
            },
        ),
    ]
