# Generated by Django 4.1.1 on 2022-10-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_round_round_number_alter_round_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
