# Generated by Django 4.1.2 on 2022-10-22 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0002_autor_livro_copialivro'),
    ]

    operations = [
        migrations.AddField(
            model_name='copialivro',
            name='emprestado_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='autor',
            name='data_de_falecimento',
            field=models.DateField(blank=True, null=True, verbose_name='Falecimento (✟)'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='data_de_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Nascimento (★)'),
        ),
    ]
