# Generated by Django 4.1.2 on 2022-10-29 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0004_alter_copialivro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpiniaoUsuarioLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('nota', models.CharField(blank=True, choices=[('1', 'Odiei'), ('2', 'Não gostei'), ('3', 'Neutro'), ('4', 'Gostei'), ('5', 'Amei')], default='3', help_text='Nota do livro segundo o usuário', max_length=1)),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.livro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'opinioes_usuarios_livros',
            },
        ),
    ]
